name: data_models
description: A starting point for Dart libraries or applications.
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  collection: ^1.19.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^5.0.0
  test: ^1.21.0
