name: knowing_root
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/data_models
  - apps/knowing_app
  - tools/parse_data
dev_dependencies:
  melos: ^6.3.2


melos:
  test:
    run: flutter test
    requires:
      flutter: true
dependencies:
  universal_io: ^2.2.2
