name: parse_data
description: A sample command-line application.
version: 0.0.0
resolution: workspace


environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  data_models: ^0.0.0
  csv: ^6.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
